### ISSUE TITLE
불필요한 파일들 삭제

### ISSUE THREAD

**Issue by snoopspy** [jise8893/pcap_test_programming#1]
one commit으로 파일들이 추가되어서 commit 내역 보기가 너무 깁니다.
https://github.com/jise8893/pcap_test_programming/commit/60b2807eb4e440e9c5ec9bde572f3fc3185a7c6e

그래서 issue에 글을 남깁니다. 아래 파일들은 git에서 삭제해 주세요. 불필요한 파일들입니다.

.qmake.stash
Makefile
main.o
pcap-test
pcap-test.pro.user

**Comment by jise8893** [comment]
수정했습니다! 감사합니다 !!

**Comment by jise8893** [comment]
넵! 알려주셔서 감사합니다!!
